# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import communicate.server.move_pb2 as move__pb2


class MoveStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPosition = channel.stream_stream(
                '/protomove.Move/GetPosition',
                request_serializer=move__pb2.StreamRequest.SerializeToString,
                response_deserializer=move__pb2.StreamResponse.FromString,
                )
        self.UnSubscribe = channel.unary_unary(
                '/protomove.Move/UnSubscribe',
                request_serializer=move__pb2.End.SerializeToString,
                response_deserializer=move__pb2.Status.FromString,
                )


class MoveServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPosition(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnSubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoveServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPosition': grpc.stream_stream_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=move__pb2.StreamRequest.FromString,
                    response_serializer=move__pb2.StreamResponse.SerializeToString,
            ),
            'UnSubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.UnSubscribe,
                    request_deserializer=move__pb2.End.FromString,
                    response_serializer=move__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protomove.Move', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Move(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPosition(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/protomove.Move/GetPosition',
            move__pb2.StreamRequest.SerializeToString,
            move__pb2.StreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnSubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protomove.Move/UnSubscribe',
            move__pb2.End.SerializeToString,
            move__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
